### PR TITLE
Removed constructor with 'serviceType' argument in UnityServiceHost.

### PR DESCRIPTION
**Pull request by luboshl**

### CODE REVIEW

**Comment by tonysneed** [comment]
We'll need to keep the original ctor for backwards compatibility.  Would not want to break existing app they use it.

**Comment by tonysneed** [comment]
Likewise, if we mark the original ctor as obsolete, existing apps would get a compiler warning. So best just to add the new ctor.

**Comment by luboshl** [comment]
Yes, it is true for `NinjectServiceHost` and `SimpleInjectorServiceHost`, but `UnityServiceHost` is **new**, no application uses it.

**Comment by luboshl** [comment]
But in `NinjectServiceHost` and `SimpleInjectorServiceHost` I can mark the old constructors as obsolete.

**Comment by luboshl** [comment]
So I marked the old constructors as `[Obsolete]` and also I switched which calls the other one. Implementation is in the new one an the old (obsolete) one call it.

**Comment by tonysneed** [comment]
I'll have a look in the morning. Thanks!

**Comment by tonysneed** [comment]
So here is the problem.  If you mark a ctor as obsolete, then compiling existing code that uses it will result in a compiler warning.

cif-ctor-obs-warning

**Comment by tonysneed** [comment]
Generic `UnityServiceHost` looks fine:

``` csharp
public class UnityServiceHost<TServiceType> : ServiceHost
    where TServiceType : class
{
    public UnityServiceHost(IUnityContainer container, params Uri[] baseAddresses)
        : base(typeof(TServiceType), baseAddresses)
```

**Comment by luboshl** [comment]
> So here is the problem. If you mark a ctor as obsolete, then compiling existing code that uses it will result in a compiler warning.

It is not a problem, it is expected behavior, isn't it? :smile: That's why `[Obsolete]` is used - to let programmer know, he should not use it and he should change it. But still it is not error but warning.

Don't we want programmers not to use the old constructor any more?

**Comment by tonysneed** [comment]
The reason that `Obsolete` generates a compiler warning is that it effectively tells the developer that the _need_ to change their code.  See this: https://msdn.microsoft.com/en-us/library/22kk2b44(v=vs.90).aspx.

So just because we add a better ctor does not mean that we should require legacy apps that they stop using the old ctor.  The new one is better, yes, but there was nothing functionally wrong with the old ctor. 

I realize this is partially a matter of preference, and my preference is not to refactor the existing code base in a way that forces existing apps to recompile in order to eliminate the compiler warning.

**Comment by tonysneed** [comment]
On the other hand, I do see your point. :smile: 

What we could do is increment the version number and just remove the old ctors.

**Comment by luboshl** [comment]
What I think is wrong with old ctor is it can be used as this:

``` C#
new SimpleInjectorServiceHost<MyService>(container, typeof(OtherService));
```

The point is, there are used two different types of service - `MyService` and `OtherService`.

But if you don'd mind to completely remove the old constructors, ok, I can remove them :smile:

**Comment by tonysneed** [comment]
OK, so let's remove them altogether, then we can bump the version.  (I may not adhere to SemVer here.)  The reason is that we are also adding a **strong name** in the new version, so there won't really be backwards compat anyways.

**Comment by luboshl** [comment]
Oh yes, also strong name, it's true. Ok, I'll remove the old ctors.

**Comment by tonysneed** [comment]
Thanks, you may now squash all your commits into one:

```
git rebase -i 0e9db40f
```

```
pick c62dd225
squash babf2495
squash ef41f917
```

Just keep the message from the picked commit:
Removed constructors with 'serviceType' argument in adapter ServiceHosts.

Remove the other messages by adding: `#` before the _unneeded_ comments when rebasing.

**Pull request merged**
