### PR TITLE
Unity Adapter

### PR DESCRIPTION
**Pull request by luboshl**
Created adapter (and WCF extension, sample and tests) for Unity.

### CODE REVIEW

**Comment by tonysneed** [comment]
I'll have a look - thanks!!

**Comment by tonysneed** [comment]
Great job!  Just squash the following commits and I'll merge:

1f9aac48
ffaa1e64

**Comment by luboshl** [comment]
Ok, commits squashed.

**Comment by luboshl** [comment]
Now I noticed that CommonInstanceFactory.Sample.Hosting.Console/app.config was automatically reformated (all attributes are inlined). Shall I put it back?

**Comment by tonysneed** [comment]
Sure, yeah go ahead.  Thanks.

**Comment by luboshl** [comment]
Done.

**Pull request merged**
